### Ordinal categorical variables

Ordinal data is a categorical, statistical data type where the variables have natural, ordered categories and the distances between the categories is not known.

For example:

Student's grade in an exam (A, B, C or Fail).
Educational level, with the categories: Elementary school, High school, College graduate, PhD ranked from 1 to 4.
When the categorical variables are ordinal, the most straightforward best approach is to replace the labels by some ordinal number based on the ranks.

In [1]:
import pandas as pd
import datetime

In [2]:
# create a variable with dates, and from that extract the weekday
# I create a list of dates with 20 days difference from today
# and then transform it into a datafame

df_base = datetime.datetime.today()
df_date_list = [df_base - datetime.timedelta(days=x) for x in range(0, 20)]
df = pd.DataFrame(df_date_list)
df.columns = ['day']
df

                          day
0  2024-01-17 17:08:27.485977
1  2024-01-16 17:08:27.485977
2  2024-01-15 17:08:27.485977
3  2024-01-14 17:08:27.485977
4  2024-01-13 17:08:27.485977
5  2024-01-12 17:08:27.485977
6  2024-01-11 17:08:27.485977
7  2024-01-10 17:08:27.485977
8  2024-01-09 17:08:27.485977
9  2024-01-08 17:08:27.485977
10 2024-01-07 17:08:27.485977
11 2024-01-06 17:08:27.485977
12 2024-01-05 17:08:27.485977
13 2024-01-04 17:08:27.485977
14 2024-01-03 17:08:27.485977
15 2024-01-02 17:08:27.485977
16 2024-01-01 17:08:27.485977
17 2023-12-31 17:08:27.485977
18 2023-12-30 17:08:27.485977
19 2023-12-29 17:08:27.485977

In [5]:

# extract the week day name

df['day_of_week'] = df['day'].dt.weekday
df.head()

                         day  day_of_week
0 2024-01-17 17:08:27.485977            2
1 2024-01-16 17:08:27.485977            1
2 2024-01-15 17:08:27.485977            0
3 2024-01-14 17:08:27.485977            6
4 2024-01-13 17:08:27.485977            5


### Ordinal Measurement Advantages
Ordinal measurement is normally used for surveys and questionnaires. Statistical analysis is applied to the responses once they are collected to place the people who took the survey into the various categories. The data is then compared to draw inferences and conclusions about the whole surveyed population with regard to the specific variables. The advantage of using ordinal measurement is ease of collation and categorization. If you ask a survey question without providing the variables, the answers are likely to be so diverse they cannot be converted to statistics.

#### With Respect to Machine Learning

Keeps the semantical information of the variable (human readable content)
Straightforward


### Ordinal Measurement Disadvantages
The same characteristics of ordinal measurement that create its advantages also create certain disadvantages. The responses are often so narrow in relation to the question that they create or magnify bias that is not factored into the survey. For example, on the question about satisfaction with the governor, people might be satisfied with his job performance but upset about a recent sex scandal. The survey question might lead respondents to state their dissatisfaction about the scandal, in spite of satisfaction with his job performance -- but the statistical conclusion will not differentiate.

With Respect to Machine Learning

Does not add machine learning valuable information